### ISSUE TITLE
Can't update the brain_grid_item template.

### ISSUE THREAD

**Issue by jan3** [bold-commerce/Brain#1]
I tried something simple like : 

```
    $( document ).ready(function() {
        window.BOLD.brain.setTemplate('brain_grid_item', '<div>product</div>', false);
    });
```

But nothing seems to happen. I am using the Brain Bold app and trying to change the template for the Related Products Widget. 

Any suggestions is much appreciated.

**Comment by jan3** [comment]
@dbertouille  Thanks for the speedy response - that has really helped me. I also discovered that `    window.BOLD.brain.app.init();` would reinit the widget, which is what I was working towards until I saw your answer here.

Sorry to diverge from the original question, but is there any documentation of the variables available in the grid item? 
Unless you can tell me how to pull in:
- Product ID
- Different Image size
-  Product link

**Comment by dbertouille** [comment]
Outside of the example we don't have any documentation describing the variables.

At the moment there isn't a way to get the product ID or different image sizes through the template variables. However, the product link can be generated from the product handle. For example,

```
  <script>
    window.BOLD = window.BOLD || {};
    window.BOLD.brain = window.BOLD.brain || {};
    window.BOLD.brain.templates = window.BOLD.brain.templates || {};
    window.BOLD.brain.templates['brain_grid_item'] = '<div><a href="/products/  {% raw %}{{ handle }}{% endraw %}">Click Me</a></div>';
  </script>
````

My example assumes the script is in a liquid file so I needed to wrap the template variable in raw/endraw.

Cheers

**Comment by jan3** [comment]
Thanks @dbertouille - This has helped me a lot! much appreciated.
